import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from 'src/app/components/resource-config/DynamicUIProps';

export interface JobIAMPolicyArgs {
  //
  jobId?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  policyData?: string;

  /*
The project in which the job belongs. If it
is not provided, the provider will use a default.
*/
  project?: string;

  /*
The region in which the job belongs. If it
is not provided, the provider will use a default.
*/
  region?: string;
}
export class JobIAMPolicy extends Resource {
  // (Computed) The etag of the jobs's IAM policy.
  public etag?: string;

  //
  public jobId?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  public policyData?: string;

  /*
The project in which the job belongs. If it
is not provided, the provider will use a default.
*/
  public project?: string;

  /*
The region in which the job belongs. If it
is not provided, the provider will use a default.
*/
  public region?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "policyData",
        "The policy data generated by a `gcp.organizations.getIAMPolicy` data source.\n\n- - -",
        [],
        true,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "project",
        "The project in which the job belongs. If it\nis not provided, the provider will use a default.",
        [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        "region",
        "The region in which the job belongs. If it\nis not provided, the provider will use a default.",
        [],
        false,
        true,
      ),
      new DynamicUIProps(InputType.String, "jobId", "", [], true, true),
    ];
  }
}
