import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from 'src/app/components/resource-config/DynamicUIProps';

export interface monitoring_AlertPolicyConditionConditionMatchedLog {
  // A logs-based filter.
  filter?: string;

  /*
A map from a label key to an extractor expression, which is used to
extract the value for this label key. Each entry in this map is
a specification for how data should be extracted from log entries that
match filter. Each combination of extracted values is treated as
a separate rule for the purposes of triggering notifications.
Label keys and corresponding values can be used in notifications
generated by this condition.
*/
  labelExtractors?: Map<string, string>;
}

export function monitoring_AlertPolicyConditionConditionMatchedLog_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.String,
      "filter",
      "A logs-based filter.",
      [],
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.Map,
      "labelExtractors",
      "A map from a label key to an extractor expression, which is used to\nextract the value for this label key. Each entry in this map is\na specification for how data should be extracted from log entries that\nmatch filter. Each combination of extracted values is treated as\na separate rule for the purposes of triggering notifications.\nLabel keys and corresponding values can be used in notifications\ngenerated by this condition.",
      InputType_Map_GetTypes(),
      false,
      false,
    ),
  ];
}
