import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import {
  securitylake_DataLakeConfiguration,
  securitylake_DataLakeConfiguration_GetTypes,
} from "../types/securitylake_DataLakeConfiguration";
import {
  securitylake_DataLakeTimeouts,
  securitylake_DataLakeTimeouts_GetTypes,
} from "../types/securitylake_DataLakeTimeouts";

export interface DataLakeArgs {
  // Specify the Region or Regions that will contribute data to the rollup region.
  configuration?: securitylake_DataLakeConfiguration;

  // The Amazon Resource Name (ARN) used to create and update the AWS Glue table. This table contains partitions generated by the ingestion and normalization of AWS log sources and custom sources.
  metaStoreManagerRoleArn?: string;

  // Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  tags?: Map<string, string>;

  //
  timeouts?: securitylake_DataLakeTimeouts;
}
export class DataLake extends Resource {
  // The ARN for the Amazon Security Lake Amazon S3 bucket.
  public s3BucketArn?: string;

  // Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  public tags?: Map<string, string>;

  // A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  public tagsAll?: Map<string, string>;

  //
  public timeouts?: securitylake_DataLakeTimeouts;

  // ARN of the Data Lake.
  public arn?: string;

  // Specify the Region or Regions that will contribute data to the rollup region.
  public configuration?: securitylake_DataLakeConfiguration;

  // The Amazon Resource Name (ARN) used to create and update the AWS Glue table. This table contains partitions generated by the ingestion and normalization of AWS log sources and custom sources.
  public metaStoreManagerRoleArn?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.Object,
        "configuration",
        "Specify the Region or Regions that will contribute data to the rollup region.",
        securitylake_DataLakeConfiguration_GetTypes(),
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "metaStoreManagerRoleArn",
        "The Amazon Resource Name (ARN) used to create and update the AWS Glue table. This table contains partitions generated by the ingestion and normalization of AWS log sources and custom sources.",
        [],
        true,
        false,
      ),
      new DynamicUIProps(
        InputType.Map,
        "tags",
        "Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.",
        InputType_Map_GetTypes(),
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.Object,
        "timeouts",
        "",
        securitylake_DataLakeTimeouts_GetTypes(),
        false,
        false,
      ),
    ];
  }
}
