import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "../../ds_base/InputType";
import { DS_Resource } from "../../ds_base/Resource";
import { DynamicUIProps } from "../../ds_base/DynamicUIProps";
import {
  efs_FileSystemProtection,
  efs_FileSystemProtection_GetTypes,
} from "../types/efs_FileSystemProtection";
import {
  efs_FileSystemLifecyclePolicy,
  efs_FileSystemLifecyclePolicy_GetTypes,
} from "../types/efs_FileSystemLifecyclePolicy";
import {
  efs_FileSystemSizeInByte,
  efs_FileSystemSizeInByte_GetTypes,
} from "../types/efs_FileSystemSizeInByte";

export interface FileSystemArgs {
  // If true, the disk will be encrypted.
  encrypted?: boolean;

  // A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.
  protection?: efs_FileSystemProtection;

  // Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.
  throughputMode?: string;

  // The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.
  provisionedThroughputInMibps?: number;

  // A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  tags?: Map<string, string>;

  // the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.
  availabilityZoneName?: string;

  /*
A unique name (a maximum of 64 characters are allowed)
used as reference when creating the Elastic File System to ensure idempotent file
system creation. By default generated by this provider. See [Elastic File System]
user guide for more information.
*/
  creationToken?: string;

  // The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
  kmsKeyId?: string;

  // A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.
  lifecyclePolicies?: Array<efs_FileSystemLifecyclePolicy>;

  // The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).
  performanceMode?: string;
}
export class FileSystem extends DS_Resource {
  // The latest known metered size (in bytes) of data stored in the file system, the value is not the exact size that the file system was at any point in time. See Size In Bytes.
  public sizeInBytes?: Array<efs_FileSystemSizeInByte>;

  // the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.
  public availabilityZoneName?: string;

  // If true, the disk will be encrypted.
  public encrypted?: boolean;

  // The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
  public kmsKeyId?: string;

  // A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.
  public lifecyclePolicies?: Array<efs_FileSystemLifecyclePolicy>;

  // The current number of mount targets that the file system has.
  public numberOfMountTargets?: number;

  // A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  public tagsAll?: Map<string, string>;

  // The identifier of the Availability Zone in which the file system's One Zone storage classes exist.
  public availabilityZoneId?: string;

  // The DNS name for the filesystem per [documented convention](http://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html).
  public dnsName?: string;

  // The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).
  public performanceMode?: string;

  // The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.
  public provisionedThroughputInMibps?: number;

  // A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  public tags?: Map<string, string>;

  // Amazon Resource Name of the file system.
  public arn?: string;

  /*
A unique name (a maximum of 64 characters are allowed)
used as reference when creating the Elastic File System to ensure idempotent file
system creation. By default generated by this provider. See [Elastic File System]
user guide for more information.
*/
  public creationToken?: string;

  // The value of the file system's `Name` tag.
  public name?: string;

  // The AWS account that created the file system. If the file system was createdby an IAM user, the parent account to which the user belongs is the owner.
  public ownerId?: string;

  // A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.
  public protection?: efs_FileSystemProtection;

  // Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.
  public throughputMode?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "throughputMode",
        "Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.",
        () => [],
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.Number,
        "provisionedThroughputInMibps",
        "The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.",
        () => [],
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "kmsKeyId",
        "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.",
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        "creationToken",
        "A unique name (a maximum of 64 characters are allowed)\nused as reference when creating the Elastic File System to ensure idempotent file\nsystem creation. By default generated by this provider. See [Elastic File System]\nuser guide for more information.",
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.Array,
        "lifecyclePolicies",
        "A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.",
        () => efs_FileSystemLifecyclePolicy_GetTypes(),
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "performanceMode",
        'The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).',
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.Bool,
        "encrypted",
        "If true, the disk will be encrypted.",
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.Object,
        "protection",
        "A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.",
        () => efs_FileSystemProtection_GetTypes(),
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.Map,
        "tags",
        "A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.",
        () => InputType_Map_GetTypes(),
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "availabilityZoneName",
        "the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.",
        () => [],
        false,
        true,
      ),
    ];
  }
}
