import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from '../../ds_base/InputType';
import { DS_Resource } from '../../ds_base/Resource';
import { DynamicUIProps } from '../../ds_base/DynamicUIProps';

export interface ClusterIAMPolicyArgs {
  /*
The name or relative resource id of the cluster to manage IAM policies for.

For `gcp.dataproc.ClusterIAMMember` or `gcp.dataproc.ClusterIAMBinding`:

- `member/members` - (Required) Identities that will be granted the privilege in `role`.
Each entry can have one of the following values:
- --allUsers--: A special identifier that represents anyone who is on the internet; with or without a Google account.
- --allAuthenticatedUsers--: A special identifier that represents anyone who is authenticated with a Google account or a service account.
- --user:{emailid}--: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
- --serviceAccount:{emailid}--: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
- --group:{emailid}--: An email address that represents a Google group. For example, admins@example.com.
- --domain:{domain}--: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
*/
  cluster?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  policyData?: string;

  /*
The project in which the cluster belongs. If it
is not provided, the provider will use a default.
*/
  project?: string;

  /*
The region in which the cluster belongs. If it
is not provided, the provider will use a default.
*/
  region?: string;
}
export class ClusterIAMPolicy extends DS_Resource {
  /*
The project in which the cluster belongs. If it
is not provided, the provider will use a default.
*/
  public project?: string;

  /*
The region in which the cluster belongs. If it
is not provided, the provider will use a default.
*/
  public region?: string;

  /*
The name or relative resource id of the cluster to manage IAM policies for.

For `gcp.dataproc.ClusterIAMMember` or `gcp.dataproc.ClusterIAMBinding`:

- `member/members` - (Required) Identities that will be granted the privilege in `role`.
Each entry can have one of the following values:
- --allUsers--: A special identifier that represents anyone who is on the internet; with or without a Google account.
- --allAuthenticatedUsers--: A special identifier that represents anyone who is authenticated with a Google account or a service account.
- --user:{emailid}--: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
- --serviceAccount:{emailid}--: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
- --group:{emailid}--: An email address that represents a Google group. For example, admins@example.com.
- --domain:{domain}--: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
*/
  public cluster?: string;

  // (Computed) The etag of the clusters's IAM policy.
  public etag?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  public policyData?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        'cluster',
        'The name or relative resource id of the cluster to manage IAM policies for.\n\nFor `gcp.dataproc.ClusterIAMMember` or `gcp.dataproc.ClusterIAMBinding`:\n\n* `member/members` - (Required) Identities that will be granted the privilege in `role`.\nEach entry can have one of the following values:\n* **allUsers**: A special identifier that represents anyone who is on the internet; with or without a Google account.\n* **allAuthenticatedUsers**: A special identifier that represents anyone who is authenticated with a Google account or a service account.\n* **user:{emailid}**: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.\n* **serviceAccount:{emailid}**: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.\n* **group:{emailid}**: An email address that represents a Google group. For example, admins@example.com.\n* **domain:{domain}**: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.',
        () => [],
        true,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        'policyData',
        'The policy data generated by a `gcp.organizations.getIAMPolicy` data source.\n\n- - -',
        () => [],
        true,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        'project',
        'The project in which the cluster belongs. If it\nis not provided, the provider will use a default.',
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        'region',
        'The region in which the cluster belongs. If it\nis not provided, the provider will use a default.',
        () => [],
        false,
        true,
      ),
    ];
  }
}
