import { InputType } from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";

export interface JobIAMPolicyArgs {
  //
  JobId?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  PolicyData?: string;

  /*
The project in which the job belongs. If it
is not provided, the provider will use a default.
*/
  Project?: string;

  /*
The region in which the job belongs. If it
is not provided, the provider will use a default.
*/
  Region?: string;
}
export class JobIAMPolicy extends Resource {
  // (Computed) The etag of the jobs's IAM policy.
  public Etag?: string;

  //
  public JobId?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  public PolicyData?: string;

  /*
The project in which the job belongs. If it
is not provided, the provider will use a default.
*/
  public Project?: string;

  /*
The region in which the job belongs. If it
is not provided, the provider will use a default.
*/
  public Region?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "Project",
        "The project in which the job belongs. If it\nis not provided, the provider will use a default.",
      ),
      new DynamicUIProps(
        InputType.String,
        "Region",
        "The region in which the job belongs. If it\nis not provided, the provider will use a default.",
      ),
      new DynamicUIProps(InputType.String, "JobId", ""),
      new DynamicUIProps(
        InputType.String,
        "PolicyData",
        "The policy data generated by a `gcp.organizations.getIAMPolicy` data source.\n\n- - -",
      ),
    ];
  }
}
