import { InputType } from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";

export interface TableIamPolicyArgs {
  // The name or relative resource id of the instance that owns the table.
  Instance?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  PolicyData?: string;

  /*
The project in which the table belongs. If it
is not provided, this provider will use the provider default.
*/
  Project?: string;

  /*
The name or relative resource id of the table to manage IAM policies for.

For `gcp.bigtable.TableIAMMember` or `gcp.bigtable.TableIAMBinding`:

- `member/members` - (Required) Identities that will be granted the privilege in `role`.
Each entry can have one of the following values:
- --allUsers--: A special identifier that represents anyone who is on the internet; with or without a Google account.
- --allAuthenticatedUsers--: A special identifier that represents anyone who is authenticated with a Google account or a service account.
- --user:{emailid}--: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
- --serviceAccount:{emailid}--: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
- --group:{emailid}--: An email address that represents a Google group. For example, admins@example.com.
- --domain:{domain}--: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
*/
  Table?: string;
}
export class TableIamPolicy extends Resource {
  // The name or relative resource id of the instance that owns the table.
  public Instance?: string;

  /*
The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

- - -
*/
  public PolicyData?: string;

  /*
The project in which the table belongs. If it
is not provided, this provider will use the provider default.
*/
  public Project?: string;

  /*
The name or relative resource id of the table to manage IAM policies for.

For `gcp.bigtable.TableIAMMember` or `gcp.bigtable.TableIAMBinding`:

- `member/members` - (Required) Identities that will be granted the privilege in `role`.
Each entry can have one of the following values:
- --allUsers--: A special identifier that represents anyone who is on the internet; with or without a Google account.
- --allAuthenticatedUsers--: A special identifier that represents anyone who is authenticated with a Google account or a service account.
- --user:{emailid}--: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
- --serviceAccount:{emailid}--: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
- --group:{emailid}--: An email address that represents a Google group. For example, admins@example.com.
- --domain:{domain}--: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
*/
  public Table?: string;

  // (Computed) The etag of the tables's IAM policy.
  public Etag?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "Instance",
        "The name or relative resource id of the instance that owns the table.",
      ),
      new DynamicUIProps(
        InputType.String,
        "PolicyData",
        "The policy data generated by a `gcp.organizations.getIAMPolicy` data source.\n\n- - -",
      ),
      new DynamicUIProps(
        InputType.String,
        "Project",
        "The project in which the table belongs. If it\nis not provided, this provider will use the provider default.",
      ),
      new DynamicUIProps(
        InputType.String,
        "Table",
        "The name or relative resource id of the table to manage IAM policies for.\n\nFor `gcp.bigtable.TableIAMMember` or `gcp.bigtable.TableIAMBinding`:\n\n* `member/members` - (Required) Identities that will be granted the privilege in `role`.\nEach entry can have one of the following values:\n* **allUsers**: A special identifier that represents anyone who is on the internet; with or without a Google account.\n* **allAuthenticatedUsers**: A special identifier that represents anyone who is authenticated with a Google account or a service account.\n* **user:{emailid}**: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.\n* **serviceAccount:{emailid}**: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.\n* **group:{emailid}**: An email address that represents a Google group. For example, admins@example.com.\n* **domain:{domain}**: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.",
      ),
    ];
  }
}
