import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from 'src/app/components/resource-config/DynamicUIProps';

export interface autoscaling_GroupInitialLifecycleHook {
  // Name of the Auto Scaling Group. By default generated by Pulumi. Conflicts with `name_prefix`.
  name?: string;

  //
  notificationMetadata?: string;

  //
  notificationTargetArn?: string;

  //
  roleArn?: string;

  //
  defaultResult?: string;

  //
  heartbeatTimeout?: number;

  //
  lifecycleTransition?: string;
}

export function autoscaling_GroupInitialLifecycleHook_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.String,
      "notificationTargetArn",
      "",
      [],
      false,
      true,
    ),
    new DynamicUIProps(InputType.String, "roleArn", "", [], false, true),
    new DynamicUIProps(InputType.String, "defaultResult", "", [], false, true),
    new DynamicUIProps(
      InputType.Number,
      "heartbeatTimeout",
      "",
      [],
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "lifecycleTransition",
      "",
      [],
      true,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "name",
      "Name of the Auto Scaling Group. By default generated by Pulumi. Conflicts with `name_prefix`.",
      [],
      true,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "notificationMetadata",
      "",
      [],
      false,
      true,
    ),
  ];
}
