import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from 'src/app/components/resource-config/DynamicUIProps';
import {
  sagemaker_FeatureGroupOfflineStoreConfigDataCatalogConfig,
  sagemaker_FeatureGroupOfflineStoreConfigDataCatalogConfig_GetTypes,
} from "./sagemaker_FeatureGroupOfflineStoreConfigDataCatalogConfig";
import {
  sagemaker_FeatureGroupOfflineStoreConfigS3StorageConfig,
  sagemaker_FeatureGroupOfflineStoreConfigS3StorageConfig_GetTypes,
} from "./sagemaker_FeatureGroupOfflineStoreConfigS3StorageConfig";

export interface sagemaker_FeatureGroupOfflineStoreConfig {
  // The meta data of the Glue table that is autogenerated when an OfflineStore is created. See Data Catalog Config Below.
  dataCatalogConfig?: sagemaker_FeatureGroupOfflineStoreConfigDataCatalogConfig;

  // Set to `true` to turn Online Store On.
  disableGlueTableCreation?: boolean;

  // The Amazon Simple Storage (Amazon S3) location of OfflineStore. See S3 Storage Config Below.
  s3StorageConfig?: sagemaker_FeatureGroupOfflineStoreConfigS3StorageConfig;

  // Format for the offline store table. Supported formats are `Glue` (Default) and Apache `Iceberg` (https://iceberg.apache.org/).
  tableFormat?: string;
}

export function sagemaker_FeatureGroupOfflineStoreConfig_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.Object,
      "dataCatalogConfig",
      "The meta data of the Glue table that is autogenerated when an OfflineStore is created. See Data Catalog Config Below.",
      sagemaker_FeatureGroupOfflineStoreConfigDataCatalogConfig_GetTypes(),
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.Bool,
      "disableGlueTableCreation",
      "Set to `true` to turn Online Store On.",
      [],
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.Object,
      "s3StorageConfig",
      "The Amazon Simple Storage (Amazon S3) location of OfflineStore. See S3 Storage Config Below.",
      sagemaker_FeatureGroupOfflineStoreConfigS3StorageConfig_GetTypes(),
      true,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "tableFormat",
      "Format for the offline store table. Supported formats are `Glue` (Default) and Apache `Iceberg` (https://iceberg.apache.org/).",
      [],
      false,
      true,
    ),
  ];
}
