import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from '../../ds_base/InputType';
import { DS_Resource } from '../../ds_base/Resource';
import { DynamicUIProps } from '../../ds_base/DynamicUIProps';

export interface SamlProviderArgs {
  // An XML document generated by an identity provider that supports SAML 2.0.
  samlMetadataDocument?: string;

  // Map of resource tags for the IAM SAML provider. .If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  tags?: Map<string, string>;

  // The name of the provider to create.
  name?: string;
}
export class SamlProvider extends DS_Resource {
  // The name of the provider to create.
  public name?: string;

  // An XML document generated by an identity provider that supports SAML 2.0.
  public samlMetadataDocument?: string;

  // Map of resource tags for the IAM SAML provider. .If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  public tags?: Map<string, string>;

  // A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  public tagsAll?: Map<string, string>;

  // The expiration date and time for the SAML provider in RFC1123 format, e.g., `Mon, 02 Jan 2006 15:04:05 MST`.
  public validUntil?: string;

  // The ARN assigned by AWS for this provider.
  public arn?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.Map,
        'tags',
        'Map of resource tags for the IAM SAML provider. .If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.',
        () => InputType_Map_GetTypes(),
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        'name',
        'The name of the provider to create.',
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        'samlMetadataDocument',
        'An XML document generated by an identity provider that supports SAML 2.0.',
        () => [],
        true,
        false,
      ),
    ];
  }
}
