import { InputType } from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";

export interface ServiceIamPolicyArgs {
  /*
The policy data generated by
a `gcp.organizations.getIAMPolicy` data source.
*/
  PolicyData?: string;

  //
  ServiceName?: string;
}
export class ServiceIamPolicy extends Resource {
  // (Computed) The etag of the IAM policy.
  public Etag?: string;

  /*
The policy data generated by
a `gcp.organizations.getIAMPolicy` data source.
*/
  public PolicyData?: string;

  //
  public ServiceName?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "PolicyData",
        "The policy data generated by\na `gcp.organizations.getIAMPolicy` data source.",
      ),
      new DynamicUIProps(InputType.String, "ServiceName", ""),
    ];
  }
}
