import { InputType } from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import { ServiceEndpoint } from "../types/ServiceEndpoint";
import { ServiceApi } from "../types/ServiceApi";

export interface ServiceArgs {
  // The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.
  ProtocOutputBase64?: string;

  /*
The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.

- - -
*/
  ServiceName?: string;

  /*
The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/api_config.yaml)).
If provided, must also provide `protoc_output_base64`.  `open_api` config must -not- be provided.
*/
  GrpcConfig?: string;

  /*
The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md).
Either this, or -both- of `grpc_config` and `protoc_output_base64` must be specified.
*/
  OpenapiConfig?: string;

  // The project ID that the service belongs to.  If not provided, provider project is used.
  Project?: string;
}
export class Service extends Resource {
  // The project ID that the service belongs to.  If not provided, provider project is used.
  public Project?: string;

  /*
The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.

- - -
*/
  public ServiceName?: string;

  // A list of Endpoint objects; structure is documented below.
  public Endpoints?: Array<ServiceEndpoint>;

  // The autogenerated ID for the configuration that is rolled out as part of the creation of this resource.  Must be provided to compute engine instances as a tag.
  public ConfigId?: string;

  // The address at which the service can be found - usually the same as the service name.
  public DnsAddress?: string;

  /*
The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/api_config.yaml)).
If provided, must also provide `protoc_output_base64`.  `open_api` config must -not- be provided.
*/
  public GrpcConfig?: string;

  /*
The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md).
Either this, or -both- of `grpc_config` and `protoc_output_base64` must be specified.
*/
  public OpenapiConfig?: string;

  // The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.
  public ProtocOutputBase64?: string;

  // A list of API objects; structure is documented below.
  public Apis?: Array<ServiceApi>;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "ProtocOutputBase64",
        "The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.",
      ),
      new DynamicUIProps(
        InputType.String,
        "ServiceName",
        "The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.\n\n- - -",
      ),
      new DynamicUIProps(
        InputType.String,
        "GrpcConfig",
        "The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/api_config.yaml)).\nIf provided, must also provide `protoc_output_base64`.  `open_api` config must *not* be provided.",
      ),
      new DynamicUIProps(
        InputType.String,
        "OpenapiConfig",
        "The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md).\nEither this, or *both* of `grpc_config` and `protoc_output_base64` must be specified.",
      ),
      new DynamicUIProps(
        InputType.String,
        "Project",
        "The project ID that the service belongs to.  If not provided, provider project is used.",
      ),
    ];
  }
}
