import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from '../../ds_base/InputType';
import { DS_Resource } from '../../ds_base/Resource';
import { DynamicUIProps } from '../../ds_base/DynamicUIProps';
import {
  endpoints_ServiceEndpoint,
  endpoints_ServiceEndpoint_GetTypes,
} from '../types/endpoints_ServiceEndpoint';
import {
  endpoints_ServiceApi,
  endpoints_ServiceApi_GetTypes,
} from '../types/endpoints_ServiceApi';

export interface ServiceArgs {
  /*
The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.

- - -
*/
  serviceName?: string;

  /*
The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/api_config.yaml)).
If provided, must also provide `protoc_output_base64`.  `open_api` config must -not- be provided.
*/
  grpcConfig?: string;

  /*
The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md).
Either this, or -both- of `grpc_config` and `protoc_output_base64` must be specified.
*/
  openapiConfig?: string;

  // The project ID that the service belongs to.  If not provided, provider project is used.
  project?: string;

  // The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.
  protocOutputBase64?: string;
}
export class Service extends DS_Resource {
  // The address at which the service can be found - usually the same as the service name.
  public dnsAddress?: string;

  // A list of Endpoint objects; structure is documented below.
  public endpoints?: Array<endpoints_ServiceEndpoint>;

  /*
The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/api_config.yaml)).
If provided, must also provide `protoc_output_base64`.  `open_api` config must -not- be provided.
*/
  public grpcConfig?: string;

  // The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.
  public protocOutputBase64?: string;

  // The autogenerated ID for the configuration that is rolled out as part of the creation of this resource.  Must be provided to compute engine instances as a tag.
  public configId?: string;

  /*
The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md).
Either this, or -both- of `grpc_config` and `protoc_output_base64` must be specified.
*/
  public openapiConfig?: string;

  // The project ID that the service belongs to.  If not provided, provider project is used.
  public project?: string;

  /*
The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.

- - -
*/
  public serviceName?: string;

  // A list of API objects; structure is documented below.
  public apis?: Array<endpoints_ServiceApi>;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        'openapiConfig',
        'The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md).\nEither this, or *both* of `grpc_config` and `protoc_output_base64` must be specified.',
        () => [],
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        'project',
        'The project ID that the service belongs to.  If not provided, provider project is used.',
        () => [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        'protocOutputBase64',
        'The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.',
        () => [],
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        'serviceName',
        'The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.\n\n- - -',
        () => [],
        true,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        'grpcConfig',
        'The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/api_config.yaml)).\nIf provided, must also provide `protoc_output_base64`.  `open_api` config must *not* be provided.',
        () => [],
        false,
        false,
      ),
    ];
  }
}
