export interface AlertPolicyConditionConditionMatchedLog {
  // A logs-based filter.
  Filter?: string;

  /*
A map from a label key to an extractor expression, which is used to
extract the value for this label key. Each entry in this map is
a specification for how data should be extracted from log entries that
match filter. Each combination of extracted values is treated as
a separate rule for the purposes of triggering notifications.
Label keys and corresponding values can be used in notifications
generated by this condition.
*/
  LabelExtractors?: Map<string, string>;
}
