export interface AlertPolicyDocumentation {
  /*
The text of the documentation, interpreted according to mimeType.
The content may not exceed 8,192 Unicode characters and may not
exceed more than 10,240 bytes when encoded in UTF-8 format,
whichever is smaller.
*/
  Content?: string;

  /*
The format of the content field. Presently, only the value
"text/markdown" is supported.
*/
  MimeType?: string;

  /*
The subject line of the notification. The subject line may not
exceed 10,240 bytes. In notifications generated by this policy the contents
of the subject line after variable expansion will be truncated to 255 bytes
or shorter at the latest UTF-8 character boundary.
*/
  Subject?: string;
}
