import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import {
  cloudbuild_TriggerBitbucketServerTriggerConfigPush,
  cloudbuild_TriggerBitbucketServerTriggerConfigPush_GetTypes,
} from "./cloudbuild_TriggerBitbucketServerTriggerConfigPush";
import {
  cloudbuild_TriggerBitbucketServerTriggerConfigPullRequest,
  cloudbuild_TriggerBitbucketServerTriggerConfigPullRequest_GetTypes,
} from "./cloudbuild_TriggerBitbucketServerTriggerConfigPullRequest";

export interface cloudbuild_TriggerBitbucketServerTriggerConfig {
  // The Bitbucket server config resource that this trigger config maps to.
  bitbucketServerConfigResource?: string;

  // Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".
  projectKey?: string;

  /*
Filter to match changes in pull requests.
Structure is documented below.
*/
  pullRequest?: cloudbuild_TriggerBitbucketServerTriggerConfigPullRequest;

  /*
Filter to match changes in refs like branches, tags.
Structure is documented below.
*/
  push?: cloudbuild_TriggerBitbucketServerTriggerConfigPush;

  /*
Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.
For example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.
*/
  repoSlug?: string;
}

export function cloudbuild_TriggerBitbucketServerTriggerConfig_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.String,
      "bitbucketServerConfigResource",
      "The Bitbucket server config resource that this trigger config maps to.",
      [],
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "projectKey",
      'Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".',
      [],
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "pullRequest",
      "Filter to match changes in pull requests.\nStructure is documented below.",
      cloudbuild_TriggerBitbucketServerTriggerConfigPullRequest_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "push",
      "Filter to match changes in refs like branches, tags.\nStructure is documented below.",
      cloudbuild_TriggerBitbucketServerTriggerConfigPush_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "repoSlug",
      "Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.\nFor example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.",
      [],
      true,
      false,
    ),
  ];
}
