import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import {
  Cloudbuild_getTriggerBitbucketServerTriggerConfigPush,
  Cloudbuild_getTriggerBitbucketServerTriggerConfigPush_GetTypes,
} from "./Cloudbuild_getTriggerBitbucketServerTriggerConfigPush";
import {
  Cloudbuild_getTriggerBitbucketServerTriggerConfigPullRequest,
  Cloudbuild_getTriggerBitbucketServerTriggerConfigPullRequest_GetTypes,
} from "./Cloudbuild_getTriggerBitbucketServerTriggerConfigPullRequest";

export interface Cloudbuild_getTriggerBitbucketServerTriggerConfig {
  // Filter to match changes in refs like branches, tags.
  Pushes?: Array<Cloudbuild_getTriggerBitbucketServerTriggerConfigPush>;

  /*
Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.
For example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.
*/
  RepoSlug?: string;

  // The Bitbucket server config resource that this trigger config maps to.
  BitbucketServerConfigResource?: string;

  // Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".
  ProjectKey?: string;

  // Filter to match changes in pull requests.
  PullRequests?: Array<Cloudbuild_getTriggerBitbucketServerTriggerConfigPullRequest>;
}

export function Cloudbuild_getTriggerBitbucketServerTriggerConfig_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.Array,
      "Pushes",
      "Filter to match changes in refs like branches, tags.",
      Cloudbuild_getTriggerBitbucketServerTriggerConfigPush_GetTypes(),
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "RepoSlug",
      "Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.\nFor example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.",
      [],
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "BitbucketServerConfigResource",
      "The Bitbucket server config resource that this trigger config maps to.",
      [],
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "ProjectKey",
      'Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".',
      [],
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.Array,
      "PullRequests",
      "Filter to match changes in pull requests.",
      Cloudbuild_getTriggerBitbucketServerTriggerConfigPullRequest_GetTypes(),
      true,
      false,
    ),
  ];
}
