import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";

export interface cloudrun_DomainMappingMetadata {
  /*
In Cloud Run the namespace must be equal to either the
project ID or project number.
*/
  namespace?: string;

  /*
(Output)
The combination of labels configured directly on the resource
and default labels configured on the provider.
*/
  pulumiLabels?: Map<string, string>;

  /*
(Output)
An opaque value that represents the internal version of this object that
can be used by clients to determine when objects have changed. May be used
for optimistic concurrency, change detection, and the watch operation on a
resource or set of resources. They may only be valid for a
particular resource or set of resources.
More info:
https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency
*/
  resourceVersion?: string;

  /*
(Output)
UID is a unique id generated by the server on successful creation of a resource and is not
allowed to change on PUT operations.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
*/
  uid?: string;

  //
  effectiveAnnotations?: Map<string, string>;

  /*
(Output)
All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Pulumi, other clients and services.
*/
  effectiveLabels?: Map<string, string>;

  /*
(Output)
A sequence number representing a specific generation of the desired state.
*/
  generation?: number;

  /*
Map of string keys and values that can be used to organize and categorize
(scope and select) objects. May match selectors of replication controllers
and routes.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
--Note--: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field `effective_labels` for all of the labels present on the resource.
*/
  labels?: Map<string, string>;

  /*
(Output)
SelfLink is a URL representing this object.
*/
  selfLink?: string;

  /*
Annotations is a key value map stored with a resource that
may be set by external tools to store and retrieve arbitrary metadata. More
info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
--Note--: The Cloud Run API may add additional annotations that were not provided in your config.
If the provider plan shows a diff where a server-side annotation is added, you can add it to your config
or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field.
--Note--: This field is non-authoritative, and will only manage the annotations present in your configuration.
Please refer to the field `effective_annotations` for all of the annotations present on the resource.
*/
  annotations?: Map<string, string>;
}

export function cloudrun_DomainMappingMetadata_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.String,
      "namespace",
      "In Cloud Run the namespace must be equal to either the\nproject ID or project number.",
      [],
      true,
      true,
    ),
    new DynamicUIProps(
      InputType.Map,
      "pulumiLabels",
      "(Output)\nThe combination of labels configured directly on the resource\nand default labels configured on the provider.",
      InputType_Map_GetTypes(),
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "resourceVersion",
      "(Output)\nAn opaque value that represents the internal version of this object that\ncan be used by clients to determine when objects have changed. May be used\nfor optimistic concurrency, change detection, and the watch operation on a\nresource or set of resources. They may only be valid for a\nparticular resource or set of resources.\nMore info:\nhttps://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Map,
      "effectiveAnnotations",
      "",
      InputType_Map_GetTypes(),
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.Map,
      "effectiveLabels",
      "(Output)\nAll of labels (key/value pairs) present on the resource in GCP, including the labels configured through Pulumi, other clients and services.",
      InputType_Map_GetTypes(),
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "uid",
      "(Output)\nUID is a unique id generated by the server on successful creation of a resource and is not\nallowed to change on PUT operations.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Number,
      "generation",
      "(Output)\nA sequence number representing a specific generation of the desired state.",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Map,
      "labels",
      "Map of string keys and values that can be used to organize and categorize\n(scope and select) objects. May match selectors of replication controllers\nand routes.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels\n**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.\nPlease refer to the field `effective_labels` for all of the labels present on the resource.",
      InputType_Map_GetTypes(),
      false,
      true,
    ),
    new DynamicUIProps(
      InputType.String,
      "selfLink",
      "(Output)\nSelfLink is a URL representing this object.",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Map,
      "annotations",
      "Annotations is a key value map stored with a resource that\nmay be set by external tools to store and retrieve arbitrary metadata. More\ninfo: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations\n**Note**: The Cloud Run API may add additional annotations that were not provided in your config.\nIf the provider plan shows a diff where a server-side annotation is added, you can add it to your config\nor apply the lifecycle.ignore_changes rule to the metadata.0.annotations field.\n**Note**: This field is non-authoritative, and will only manage the annotations present in your configuration.\nPlease refer to the field `effective_annotations` for all of the annotations present on the resource.",
      InputType_Map_GetTypes(),
      false,
      true,
    ),
  ];
}
