import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import {
  Compute_RegionUrlMapDefaultRouteActionUrlRewrite,
  Compute_RegionUrlMapDefaultRouteActionUrlRewrite_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionUrlRewrite";
import {
  Compute_RegionUrlMapDefaultRouteActionWeightedBackendService,
  Compute_RegionUrlMapDefaultRouteActionWeightedBackendService_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionWeightedBackendService";
import {
  Compute_RegionUrlMapDefaultRouteActionCorsPolicy,
  Compute_RegionUrlMapDefaultRouteActionCorsPolicy_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionCorsPolicy";
import {
  Compute_RegionUrlMapDefaultRouteActionFaultInjectionPolicy,
  Compute_RegionUrlMapDefaultRouteActionFaultInjectionPolicy_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionFaultInjectionPolicy";
import {
  Compute_RegionUrlMapDefaultRouteActionRequestMirrorPolicy,
  Compute_RegionUrlMapDefaultRouteActionRequestMirrorPolicy_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionRequestMirrorPolicy";
import {
  Compute_RegionUrlMapDefaultRouteActionRetryPolicy,
  Compute_RegionUrlMapDefaultRouteActionRetryPolicy_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionRetryPolicy";
import {
  Compute_RegionUrlMapDefaultRouteActionTimeout,
  Compute_RegionUrlMapDefaultRouteActionTimeout_GetTypes,
} from "./Compute_RegionUrlMapDefaultRouteActionTimeout";

export interface Compute_RegionUrlMapDefaultRouteAction {
  /*
Specifies the policy on how requests intended for the route's backends are shadowed to a separate mirrored backend service.
The load balancer does not wait for responses from the shadow service. Before sending traffic to the shadow service, the host / authority header is suffixed with -shadow.
Not supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.
Structure is documented below.
*/
  RequestMirrorPolicy?: Compute_RegionUrlMapDefaultRouteActionRequestMirrorPolicy;

  /*
Specifies the retry policy associated with this route.
Structure is documented below.
*/
  RetryPolicy?: Compute_RegionUrlMapDefaultRouteActionRetryPolicy;

  /*
Specifies the timeout for the selected route. Timeout is computed from the time the request has been fully processed (known as end-of-stream) up until the response has been processed. Timeout includes all retries.
If not specified, this field uses the largest timeout among all backend services associated with the route.
Not supported when the URL map is bound to a target gRPC proxy that has validateForProxyless field set to true.
Structure is documented below.
*/
  Timeout?: Compute_RegionUrlMapDefaultRouteActionTimeout;

  /*
The spec to modify the URL of the request, before forwarding the request to the matched service.
urlRewrite is the only action supported in UrlMaps for external HTTP(S) load balancers.
Not supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.
Structure is documented below.
*/
  UrlRewrite?: Compute_RegionUrlMapDefaultRouteActionUrlRewrite;

  /*
A list of weighted backend services to send traffic to when a route match occurs. The weights determine the fraction of traffic that flows to their corresponding backend service. If all traffic needs to go to a single backend service, there must be one weightedBackendService with weight set to a non-zero number.
After a backend service is identified and before forwarding the request to the backend service, advanced routing actions such as URL rewrites and header transformations are applied depending on additional settings specified in this HttpRouteAction.
Structure is documented below.
*/
  WeightedBackendServices?: Array<Compute_RegionUrlMapDefaultRouteActionWeightedBackendService>;

  /*
The specification for allowing client side cross-origin requests. Please see
[W3C Recommendation for Cross Origin Resource Sharing](https://www.w3.org/TR/cors/)
Structure is documented below.
*/
  CorsPolicy?: Compute_RegionUrlMapDefaultRouteActionCorsPolicy;

  /*
The specification for fault injection introduced into traffic to test the resiliency of clients to backend service failure.
As part of fault injection, when clients send requests to a backend service, delays can be introduced by a load balancer on a percentage of requests before sending those requests to the backend service.
Similarly requests from clients can be aborted by the load balancer for a percentage of requests.
timeout and retryPolicy is ignored by clients that are configured with a faultInjectionPolicy if: 1. The traffic is generated by fault injection AND 2. The fault injection is not a delay fault injection.
Fault injection is not supported with the global external HTTP(S) load balancer (classic). To see which load balancers support fault injection, see Load balancing: [Routing and traffic management features](https://cloud.google.com/load-balancing/docs/features#routing-traffic-management).
Structure is documented below.
*/
  FaultInjectionPolicy?: Compute_RegionUrlMapDefaultRouteActionFaultInjectionPolicy;
}

export function Compute_RegionUrlMapDefaultRouteAction_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.Object,
      "FaultInjectionPolicy",
      "The specification for fault injection introduced into traffic to test the resiliency of clients to backend service failure.\nAs part of fault injection, when clients send requests to a backend service, delays can be introduced by a load balancer on a percentage of requests before sending those requests to the backend service.\nSimilarly requests from clients can be aborted by the load balancer for a percentage of requests.\ntimeout and retryPolicy is ignored by clients that are configured with a faultInjectionPolicy if: 1. The traffic is generated by fault injection AND 2. The fault injection is not a delay fault injection.\nFault injection is not supported with the global external HTTP(S) load balancer (classic). To see which load balancers support fault injection, see Load balancing: [Routing and traffic management features](https://cloud.google.com/load-balancing/docs/features#routing-traffic-management).\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionFaultInjectionPolicy_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "RequestMirrorPolicy",
      "Specifies the policy on how requests intended for the route's backends are shadowed to a separate mirrored backend service.\nThe load balancer does not wait for responses from the shadow service. Before sending traffic to the shadow service, the host / authority header is suffixed with -shadow.\nNot supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionRequestMirrorPolicy_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "RetryPolicy",
      "Specifies the retry policy associated with this route.\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionRetryPolicy_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "Timeout",
      "Specifies the timeout for the selected route. Timeout is computed from the time the request has been fully processed (known as end-of-stream) up until the response has been processed. Timeout includes all retries.\nIf not specified, this field uses the largest timeout among all backend services associated with the route.\nNot supported when the URL map is bound to a target gRPC proxy that has validateForProxyless field set to true.\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionTimeout_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "UrlRewrite",
      "The spec to modify the URL of the request, before forwarding the request to the matched service.\nurlRewrite is the only action supported in UrlMaps for external HTTP(S) load balancers.\nNot supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionUrlRewrite_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Array,
      "WeightedBackendServices",
      "A list of weighted backend services to send traffic to when a route match occurs. The weights determine the fraction of traffic that flows to their corresponding backend service. If all traffic needs to go to a single backend service, there must be one weightedBackendService with weight set to a non-zero number.\nAfter a backend service is identified and before forwarding the request to the backend service, advanced routing actions such as URL rewrites and header transformations are applied depending on additional settings specified in this HttpRouteAction.\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionWeightedBackendService_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "CorsPolicy",
      "The specification for allowing client side cross-origin requests. Please see\n[W3C Recommendation for Cross Origin Resource Sharing](https://www.w3.org/TR/cors/)\nStructure is documented below.",
      Compute_RegionUrlMapDefaultRouteActionCorsPolicy_GetTypes(),
      false,
      false,
    ),
  ];
}
