export interface DomainMappingMetadata {
  //
  EffectiveAnnotations?: Map<string, string>;

  /*
In Cloud Run the namespace must be equal to either the
project ID or project number.
*/
  Namespace?: string;

  /*
(Output)
The combination of labels configured directly on the resource
and default labels configured on the provider.
*/
  PulumiLabels?: Map<string, string>;

  /*
(Output)
An opaque value that represents the internal version of this object that
can be used by clients to determine when objects have changed. May be used
for optimistic concurrency, change detection, and the watch operation on a
resource or set of resources. They may only be valid for a
particular resource or set of resources.
More info:
https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency
*/
  ResourceVersion?: string;

  /*
(Output)
SelfLink is a URL representing this object.
*/
  SelfLink?: string;

  /*
Annotations is a key value map stored with a resource that
may be set by external tools to store and retrieve arbitrary metadata. More
info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
--Note--: The Cloud Run API may add additional annotations that were not provided in your config.
If the provider plan shows a diff where a server-side annotation is added, you can add it to your config
or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field.
--Note--: This field is non-authoritative, and will only manage the annotations present in your configuration.
Please refer to the field `effective_annotations` for all of the annotations present on the resource.
*/
  Annotations?: Map<string, string>;

  /*
(Output)
All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Pulumi, other clients and services.
*/
  EffectiveLabels?: Map<string, string>;

  /*
(Output)
A sequence number representing a specific generation of the desired state.
*/
  Generation?: number;

  /*
Map of string keys and values that can be used to organize and categorize
(scope and select) objects. May match selectors of replication controllers
and routes.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
--Note--: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field `effective_labels` for all of the labels present on the resource.
*/
  Labels?: Map<string, string>;

  /*
(Output)
UID is a unique id generated by the server on successful creation of a resource and is not
allowed to change on PUT operations.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
*/
  Uid?: string;
}
