import { FeatureMembershipPolicycontrollerPolicyControllerHubConfigPolicyContentTemplateLibrary } from "./FeatureMembershipPolicycontrollerPolicyControllerHubConfigPolicyContentTemplateLibrary";

export interface FeatureMembershipPolicycontrollerPolicyControllerHubConfigPolicyContent {
  // Configures the installation of the Template Library. Structure is documented below.
  TemplateLibrary?: FeatureMembershipPolicycontrollerPolicyControllerHubConfigPolicyContentTemplateLibrary;
}
