export interface getServiceTemplateMetadata {
  /*
Map of string keys and values that can be used to organize and categorize
(scope and select) objects.
*/
  Labels?: Map<string, string>;

  // The name of the Cloud Run Service.
  Name?: string;

  /*
In Cloud Run the namespace must be equal to either the
project ID or project number. It will default to the resource's project.
*/
  Namespace?: string;

  /*
An opaque value that represents the internal version of this object that
can be used by clients to determine when objects have changed. May be used
for optimistic concurrency, change detection, and the watch operation on a
resource or set of resources. They may only be valid for a
particular resource or set of resources.
*/
  ResourceVersion?: string;

  // SelfLink is a URL representing this object.
  SelfLink?: string;

  /*
UID is a unique id generated by the server on successful creation of a resource and is not
allowed to change on PUT operations.
*/
  Uid?: string;

  //
  Annotations?: Map<string, string>;

  // A sequence number representing a specific generation of the desired state.
  Generation?: number;
}
