export interface getServiceMetadata {
  //
  EffectiveLabels?: Map<string, string>;

  // A sequence number representing a specific generation of the desired state.
  Generation?: number;

  /*
Map of string keys and values that can be used to organize and categorize
(scope and select) objects. May match selectors of replication controllers
and routes.

--Note--: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field 'effective_labels' for all of the labels present on the resource.
*/
  Labels?: Map<string, string>;

  /*
An opaque value that represents the internal version of this object that
can be used by clients to determine when objects have changed. May be used
for optimistic concurrency, change detection, and the watch operation on a
resource or set of resources. They may only be valid for a
particular resource or set of resources.
*/
  ResourceVersion?: string;

  //
  Annotations?: Map<string, string>;

  //
  EffectiveAnnotations?: Map<string, string>;

  // SelfLink is a URL representing this object.
  SelfLink?: string;

  /*
UID is a unique id generated by the server on successful creation of a resource and is not
allowed to change on PUT operations.
*/
  Uid?: string;

  /*
In Cloud Run the namespace must be equal to either the
project ID or project number.
*/
  Namespace?: string;

  /*
The combination of labels configured directly on the resource
 and default labels configured on the provider.
*/
  PulumiLabels?: Map<string, string>;
}
