export interface JobPlacement {
  // Output-only. A cluster UUID generated by the Cloud Dataproc service when the job is submitted
  ClusterUuid?: string;

  // The name of the cluster where the job will be submitted
  ClusterName?: string;
}
