import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";

export interface Monitoring_AlertPolicyDocumentation {
  /*
The text of the documentation, interpreted according to mimeType.
The content may not exceed 8,192 Unicode characters and may not
exceed more than 10,240 bytes when encoded in UTF-8 format,
whichever is smaller.
*/
  Content?: string;

  /*
The format of the content field. Presently, only the value
"text/markdown" is supported.
*/
  MimeType?: string;

  /*
The subject line of the notification. The subject line may not
exceed 10,240 bytes. In notifications generated by this policy the contents
of the subject line after variable expansion will be truncated to 255 bytes
or shorter at the latest UTF-8 character boundary.
*/
  Subject?: string;
}

export function Monitoring_AlertPolicyDocumentation_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.String,
      "Content",
      "The text of the documentation, interpreted according to mimeType.\nThe content may not exceed 8,192 Unicode characters and may not\nexceed more than 10,240 bytes when encoded in UTF-8 format,\nwhichever is smaller.",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "MimeType",
      'The format of the content field. Presently, only the value\n"text/markdown" is supported.',
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "Subject",
      "The subject line of the notification. The subject line may not\nexceed 10,240 bytes. In notifications generated by this policy the contents\nof the subject line after variable expansion will be truncated to 255 bytes\nor shorter at the latest UTF-8 character boundary.",
      [],
      false,
      false,
    ),
  ];
}
