import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import {
  Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigCustomOutput,
  Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigCustomOutput_GetTypes,
} from "./Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigCustomOutput";
import {
  Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigPredicate,
  Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigPredicate_GetTypes,
} from "./Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigPredicate";
import {
  Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigResourceSelector,
  Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigResourceSelector_GetTypes,
} from "./Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigResourceSelector";

export interface Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfig {
  /*
Custom output properties. A set of optional name-value pairs that define custom source properties to
return with each finding that is generated by the custom module. The custom
source properties that are defined here are included in the finding JSON
under `sourceProperties`.
Structure is documented below.
*/
  CustomOutput?: Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigCustomOutput;

  /*
Text that describes the vulnerability or misconfiguration that the custom
module detects.
*/
  Description?: string;

  /*
The CEL expression to evaluate to produce findings.When the expression
evaluates to true against a resource, a finding is generated.
Structure is documented below.
*/
  Predicate?: Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigPredicate;

  /*
An explanation of the recommended steps that security teams can take to
resolve the detected issue
*/
  Recommendation?: string;

  /*
The resource types that the custom module operates on. Each custom module
can specify up to 5 resource types.
Structure is documented below.
*/
  ResourceSelector?: Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigResourceSelector;

  /*
The severity to assign to findings generated by the module.
Possible values are: `SEVERITY_UNSPECIFIED`, `CRITICAL`, `HIGH`, `MEDIUM`, `LOW`.
*/
  Severity?: string;
}

export function Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfig_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.Object,
      "CustomOutput",
      "Custom output properties. A set of optional name-value pairs that define custom source properties to\nreturn with each finding that is generated by the custom module. The custom\nsource properties that are defined here are included in the finding JSON\nunder `sourceProperties`.\nStructure is documented below.",
      Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigCustomOutput_GetTypes(),
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "Description",
      "Text that describes the vulnerability or misconfiguration that the custom\nmodule detects.",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "Predicate",
      "The CEL expression to evaluate to produce findings.When the expression\nevaluates to true against a resource, a finding is generated.\nStructure is documented below.",
      Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigPredicate_GetTypes(),
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "Recommendation",
      "An explanation of the recommended steps that security teams can take to\nresolve the detected issue",
      [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.Object,
      "ResourceSelector",
      "The resource types that the custom module operates on. Each custom module\ncan specify up to 5 resource types.\nStructure is documented below.",
      Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigResourceSelector_GetTypes(),
      true,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "Severity",
      "The severity to assign to findings generated by the module.\nPossible values are: `SEVERITY_UNSPECIFIED`, `CRITICAL`, `HIGH`, `MEDIUM`, `LOW`.",
      [],
      true,
      false,
    ),
  ];
}
