import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "../../ds_base/InputType";
import { DynamicUIProps } from "../../ds_base/DynamicUIProps";

export interface vertex_AiFeatureStoreEntityTypeMonitoringConfigImportFeaturesAnalysis {
  /*
Defines the baseline to do anomaly detection for feature values imported by each [entityTypes.importFeatureValues][] operation. The value must be one of the values below:
- LATEST_STATS: Choose the later one statistics generated by either most recent snapshot analysis or previous import features analysis. If non of them exists, skip anomaly detection and only generate a statistics.
- MOST_RECENT_SNAPSHOT_STATS: Use the statistics generated by the most recent snapshot analysis if exists.
- PREVIOUS_IMPORT_FEATURES_STATS: Use the statistics generated by the previous import features analysis if exists.
*/
  anomalyDetectionBaseline?: string;

  /*
Whether to enable / disable / inherite default hebavior for import features analysis. The value must be one of the values below:
- DEFAULT: The default behavior of whether to enable the monitoring. EntityType-level config: disabled.
- ENABLED: Explicitly enables import features analysis. EntityType-level config: by default enables import features analysis for all Features under it.
- DISABLED: Explicitly disables import features analysis. EntityType-level config: by default disables import features analysis for all Features under it.
*/
  state?: string;
}

export function vertex_AiFeatureStoreEntityTypeMonitoringConfigImportFeaturesAnalysis_GetTypes(): DynamicUIProps[] {
  return [
    new DynamicUIProps(
      InputType.String,
      "state",
      "Whether to enable / disable / inherite default hebavior for import features analysis. The value must be one of the values below:\n* DEFAULT: The default behavior of whether to enable the monitoring. EntityType-level config: disabled.\n* ENABLED: Explicitly enables import features analysis. EntityType-level config: by default enables import features analysis for all Features under it.\n* DISABLED: Explicitly disables import features analysis. EntityType-level config: by default disables import features analysis for all Features under it.",
      () => [],
      false,
      false,
    ),
    new DynamicUIProps(
      InputType.String,
      "anomalyDetectionBaseline",
      "Defines the baseline to do anomaly detection for feature values imported by each [entityTypes.importFeatureValues][] operation. The value must be one of the values below:\n* LATEST_STATS: Choose the later one statistics generated by either most recent snapshot analysis or previous import features analysis. If non of them exists, skip anomaly detection and only generate a statistics.\n* MOST_RECENT_SNAPSHOT_STATS: Use the statistics generated by the most recent snapshot analysis if exists.\n* PREVIOUS_IMPORT_FEATURES_STATS: Use the statistics generated by the previous import features analysis if exists.",
      () => [],
      false,
      false,
    ),
  ];
}
