import { WorkflowTemplatePlacementManagedClusterConfigSecurityConfigKerberosConfig } from "./WorkflowTemplatePlacementManagedClusterConfigSecurityConfigKerberosConfig";

export interface WorkflowTemplatePlacementManagedClusterConfigSecurityConfig {
  // Kerberos related configuration.
  KerberosConfig?: WorkflowTemplatePlacementManagedClusterConfigSecurityConfigKerberosConfig;
}
