export interface WorkflowTemplatePlacementManagedClusterConfigSecurityConfigKerberosConfig {
  // The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship.
  CrossRealmTrustSharedPassword?: string;

  // The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc.
  TruststorePassword?: string;

  // The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
  CrossRealmTrustKdc?: string;

  // The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust.
  CrossRealmTrustRealm?: string;

  // The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database.
  KdcDbKey?: string;

  // The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc.
  KeystorePassword?: string;

  // The lifetime of the ticket granting ticket, in hours. If not specified, or user specifies 0, then default value 10 will be used.
  TgtLifetimeHours?: number;

  // The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
  Truststore?: string;

  // The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
  CrossRealmTrustAdminServer?: string;

  // The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
  Keystore?: string;

  // The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm.
  Realm?: string;

  // The Cloud Storage URI of a KMS encrypted file containing the root principal password.
  RootPrincipalPassword?: string;

  // Flag to indicate whether to Kerberize the cluster (default: false). Set this field to true to enable Kerberos on a cluster.
  EnableKerberos?: boolean;

  // The uri of the KMS key used to encrypt various sensitive files.
  KmsKey?: string;

  // The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc.
  KeyPassword?: string;
}
