import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from "src/app/components/resource-config/resource-config.component";
import {
  Diagflow_CxVersionNluSetting,
  Diagflow_CxVersionNluSetting_GetTypes,
} from "../types/Diagflow_CxVersionNluSetting";

export interface CxVersionArgs {
  // The description of the version. The maximum length is 500 characters. If exceeded, the request is rejected.
  Description?: string;

  /*
The human-readable name of the version. Limit of 64 characters.


- - -
*/
  DisplayName?: string;

  /*
The Flow to create an Version for.
Format: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>.
*/
  Parent?: string;
}
export class CxVersion extends Resource {
  /*
The NLU settings of the flow at version creation.
Structure is documented below.
*/
  public NluSettings?: Array<Diagflow_CxVersionNluSetting>;

  /*
The Flow to create an Version for.
Format: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>.
*/
  public Parent?: string;

  /*
The state of this version.
- RUNNING: Version is not ready to serve (e.g. training is running).
- SUCCEEDED: Training has succeeded and this version is ready to serve.
- FAILED: Version training failed.
*/
  public State?: string;

  // A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits. Examples: "2014-10-02T15:01:23Z" and "2014-10-02T15:01:23.045123456Z".
  public CreateTime?: string;

  // The description of the version. The maximum length is 500 characters. If exceeded, the request is rejected.
  public Description?: string;

  /*
The human-readable name of the version. Limit of 64 characters.


- - -
*/
  public DisplayName?: string;

  // Format: projects//locations//agents//flows//versions/. Version ID is a self-increasing number generated by Dialogflow upon version creation.
  public Name?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "Description",
        "The description of the version. The maximum length is 500 characters. If exceeded, the request is rejected.",
        [],
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "DisplayName",
        "The human-readable name of the version. Limit of 64 characters.\n\n\n- - -",
        [],
        true,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "Parent",
        "The Flow to create an Version for.\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>.",
        [],
        false,
        true,
      ),
    ];
  }
}
