import {
  InputType,
  InputType_String_GetTypes,
  InputType_Number_GetTypes,
  InputType_Map_GetTypes,
} from "src/app/enum/InputType";
import { Resource } from "src/app/Models/CloudResource";
import { DynamicUIProps } from 'src/app/components/resource-config/DynamicUIProps';

export interface PublicKeyArgs {
  // An optional comment about the public key.
  comment?: string;

  // The encoded public key that you want to add to CloudFront to use with features like field-level encryption.
  encodedKey?: string;

  // The name for the public key. By default generated by this provider.
  name?: string;

  /*
The name for the public key. Conflicts with `name`.

--NOTE:-- When setting `encoded_key` value, there needs a newline at the end of string. Otherwise, multiple runs of pulumi will want to recreate the `aws.cloudfront.PublicKey` resource.
*/
  namePrefix?: string;
}
export class PublicKey extends Resource {
  // Internal value used by CloudFront to allow future updates to the public key configuration.
  public callerReference?: string;

  // An optional comment about the public key.
  public comment?: string;

  // The encoded public key that you want to add to CloudFront to use with features like field-level encryption.
  public encodedKey?: string;

  // The current version of the public key. For example: `E2QWRUHAPOMQZL`.
  public etag?: string;

  // The name for the public key. By default generated by this provider.
  public name?: string;

  /*
The name for the public key. Conflicts with `name`.

--NOTE:-- When setting `encoded_key` value, there needs a newline at the end of string. Otherwise, multiple runs of pulumi will want to recreate the `aws.cloudfront.PublicKey` resource.
*/
  public namePrefix?: string;

  public static GetTypes(): DynamicUIProps[] {
    return [
      new DynamicUIProps(
        InputType.String,
        "comment",
        "An optional comment about the public key.",
        [],
        false,
        false,
      ),
      new DynamicUIProps(
        InputType.String,
        "encodedKey",
        "The encoded public key that you want to add to CloudFront to use with features like field-level encryption.",
        [],
        true,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        "name",
        "The name for the public key. By default generated by this provider.",
        [],
        false,
        true,
      ),
      new DynamicUIProps(
        InputType.String,
        "namePrefix",
        "The name for the public key. Conflicts with `name`.\n\n**NOTE:** When setting `encoded_key` value, there needs a newline at the end of string. Otherwise, multiple runs of pulumi will want to recreate the `aws.cloudfront.PublicKey` resource.",
        [],
        false,
        true,
      ),
    ];
  }
}
