name: Trigger UI File Update In Server Repo

on:
  workflow_dispatch:

jobs:
  Trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Server Repo
        run: |
          repo_owner="DesignPlain" 
          repo_name="PlainServer"  
          event_type="Trigger-UI-File-Update" 

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ORG_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
